language: generic
sudo: required
dist: trusty

services:
- docker

env:
- BUILDER_NAME="external-lb/${TRAVIS_JOB_ID}builder"

install:
 - git reset --hard

script:
- make docker-test

deploy:
- provider: script
  script: $DOCKER_LOGIN && make docker-push
  skip_cleanup: true
  on:
    branch: master