apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: providers.manager.external-loadbalancer
spec:
  group: manager.external-loadbalancer
  names:
    kind: Provider
    plural: providers
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            default:
              type: boolean
            internal:
              type: boolean
            url:
              type: string
          required:
          - url
          type: object
        status:
          properties:
            connectionStatus:
              type: string
          type: object
  version: v1alpha1